### ISSUE TITLE
Auto-Mute Not Removing in Proximity to Others

### ISSUE THREAD

**Issue by F4ngb0n3** [carlodrift/skoice#19] opened 2022-02-07 21:28 UTC
The plugin works very well aside from a single use-case and thats me; don't know if it's because I set it up, but regardless of if I am in proximity to others, my VC doesn't get the server mute removed. I can hear players speaking, but they have to tell me I am muted or I am unaware. Any resolution for this?

When I first join, its 50-50 on if it auto-removes the mute with other players around. If I am out and about, and another player comes near me, it doesn't remove it about 85% of the time.

**Comment by matthewromeroskytap** [comment] 2022-02-07 23:19
i also have this issue

**Comment by F4ngb0n3** [comment] 2022-02-09 15:51
Yes. There were resets, but after everyone had disconnected. I was so excited I didnt want to break it, so I booted everyone from server and Discord before stopping and starting the server up again.

**Comment by carlodrift** [comment] 2022-02-13 13:01
The players that were muted aren't kept between restarts and the bot cannot unmute users when they aren't connected to a voice channel, so if they leave whilst in the lobby this will happen. This feature intentionally only mutes users who can also unmute theirselves, so if this happens they can just unmute theirselves. Keep in mind that users who do not override speaking permission restrictions in the voice lobby will not be server muted and are not affected by this

**Comment by F4ngb0n3** [comment] 2022-02-14 15:51
So, as I am the server admin in Discord, this feature will happen to me exclusively? None of my other community members have experienced a mute that wasnt removed when in proximity to others; as the admin, I am the only one. Will this be a regular thing? Is there a way for me to remove it so I don't have to tab out all the time and unmute myself?

**Comment by carlodrift** [comment] 2022-02-14 15:58
Only users who can bypass the channel mute are impacted by the mute system. Do you ever have no mute problem and suddenly get muted without restarting the Minecraft server in between?

**Comment by F4ngb0n3** [comment] 2022-02-14 16:11
No that hasn't occured yet. Only I get server muted and stay muted. All other players are able to have it switch back and forth automatically

**Comment by Matt2021-A** [comment] 2022-02-14 16:29
i have the same issue - 100% only myself and the other Admin has this issue - and it did not exist prior to implementing Skoice, its annoying to be sure, but at least the service works great for all the other players.

**Comment by carlodrift** [comment] 2022-02-14 18:56
The problem occurs after a restart of the Minecraft server when you use Skoice and if you unmute manually, the problem is solved, right?

**Comment by Matt2021-A** [comment] 2022-02-14 19:46
until you re-join the voice channel again - even without a reboot. it seems that it happens on connecting to the voice channel.. once you've unmuted it works the remainder of the session your connected to as expected - but if you disconnect, and then re-connect to the channel again - server muted again.

**Comment by LucasCdry** [comment] 2022-05-27 22:04
Hey! This has been resolved in the next version of Skoice that is soon to be available. Thank you for reporting the issue.

**Closed by LucasCdry** 2022-05-27 22:04 UTC
Labels: bug
